### ISSUE TITLE
Efeito acumulado na animação na barra de navegação

### ISSUE THREAD

**Issue by caiotarifa** [univesp/eu-gestor#1]
Olá,

Sou aluno da UNIVESP e fiquei muito feliz em ver mais de código aberto por aqui, refletindo exatamente os valores que eu acredito para esta universidade. Parabéns! O projeto ficou excelente e, além de bonito, é possível perceber o cuidado dos desenvolvedores em detalhes importantes, como o caso da acessibilidade.

Aproveitando, gostaria de fornecer um feedback em relação à animação de rolagem associada à barra de navegação. Veja abaixo o problema da animação acumulada.

![ezgif-1-bc99d0115b59](https://user-images.githubusercontent.com/197979/53465152-786e2580-3a2b-11e9-8958-722bcb43e9e8.gif)

Minha proposta de solução seria utilizar alguma técnica como _throttle_ ou _debounce_.

Obrigado!

**Comment by bgarabs** [comment]
Olá, Caio!

Também ficamos muito felizes com o seu feedback 😄 
Seguimos sua sugestão e acreditamos ter resolvido o problema.

Obrigada pela colaboração!

**Comment by caiotarifa** [comment]
Maravilha, obrigado! :)
